### ISSUE TITLE
submission to flathub

### ISSUE THREAD

**Issue by LithRakoon** [Thelolguy1/grapejuice-flatpak#15]
Will you create a submission for flathub now that its in a playable state?
this way user would have an easier time getting grapejuice and start playing roblox.
Imo this should be the next goal

**Comment by Thelolguy1** [comment]
Absolutely, I'm looking for auditors/reviewers who can point to flaws in my code that are in violation of:

https://github.com/flathub/flathub/wiki/App-Submission

**Comment by Thelolguy1** [comment]
Unfortunately, it seems that Brinker doesn't want it to be on the flathub, at least for now.

![image](https://user-images.githubusercontent.com/18731514/174916352-4e62ec56-4d1d-496e-add0-932afbf79cfc.png)

I'll close this issue until the decision is changed.

**Comment by ramcq** [comment]
Hi, Flathub guy here, with an interest at work in having Grapejuice on Flathub... :) Some projects like OBS Studio, Firefox, etc have their own CI/CD flow which uploads the Flatpak into Flathub, meaning the build/publishing is driven from your own GitHub org rather than needing the separate repo under the Flathub org. Would this be something worth discussing/investigating?

**Comment by Thelolguy1** [comment]
Personally, I think this flatpak would be great on flathub, but Brinker, the original developer of Grapejuice, has voiced some opposition against doing so.

Currently, one of the major issues with this flatpak is the requirement for users to first install org.winehq.Wine from flathub. For some odd reason, GL32 and other 32-bit dependencies aren't resolved and installed from flathub automatically. This issue would be solved by placing this flatpak on flathub.

I've requested that Brinker join this issue discussion, so that we can consider future actions properly.

Thanks @ramcq for your inquiry.

**Comment by Thelolguy1** [comment]
@ramcq 
![image](https://user-images.githubusercontent.com/18731514/177225320-0ca93f85-2c46-4899-ac45-6a6c4998c522.png)
Brinker has given me the go ahead to submit grapejuice to flathub, so I will begin work ASAP. Additionally, would you please let me know more about the CI/CD workflow?

Thanks

**Comment by ramcq** [comment]
Great news. The usual way is to use a repo under Flathub (where the Flathub buildbot monitors, builds and pushes to Flathub) - then you could use a GitHub action to push an update to the app on Flathub when there is an upstream release. Alternatively, you can get tokens to push directly to the ostree repo, which is what OBS does. https://github.com/flatpak/flatpak-github-actions are the github actions to build Flatpaks on demand, and https://github.com/obsproject/obs-studio/pull/5569 is the example of how OBS does it. Alternatively in GitLab, this kind of flow can be used to build and push a Flatpak - https://gitlab.gnome.org/GNOME/citemplates/-/blob/master/flatpak/flatpak_ci_initiative.yml

**Comment by lunarlattice0** [comment]
@ramcq Hello, I've finalized a flathub pull for [grapejuice](https://github.com/flathub/flathub/pull/3328), and it is fully ready to go. Approximately how long will it take before the new branch will be merged?
Thanks

**Comment by lunarlattice0** [comment]
[It's now merged!](https://github.com/flathub/net.brinkervii.grapejuice)

**Comment by ramcq** [comment]
Amazing news! Congrats and thanks @Thelolguy1 :partying_face:

**Comment by lunarlattice0** [comment]
Thanks!
